all:
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: /Users/evan/evan/DevOps/id_rsa
  children:
    prod:
      hosts:
        evan.chinnaya.takima.cloud  # Remplacez ceci par le nom de votre hôte ou son adresse IP

